### ISSUE TITLE
Compiler data for the prime number calculator

### ISSUE THREAD

**Issue by dested** [dagothar/wireworld-compiler#1]
Hey there! Great project. I was wondering if you had the compiler values needed to run the prime number calculator from the wireworld computer paper?

Thanks!

**Comment by dagothar** [comment]
Hi, Thanks!. The prime number calculator code is available on the original Quinapalus page here: https://quinapalus.com/wires11.html

I hope it still works ;)

Cheers!

**Comment by dested** [comment]
It works, and its glorious. Thanks!

```001e
361f
2021
3c22
3d23
3c3d
3d20
3924
3725
383d
3f38
3d3d
3d3d
353d
3926
3727
3836
3f38
3928
0020
3d20
3c1e
3f29
203d
    
    
    
    
    
0002
7fff
0005
0003
fffe
fffd
0014
000d
0009
0005
0015
0004
fffc

**Comment by dagothar** [comment]
That's great! Let me know if you implement something new.
